image: java:8-jdk

stages:
  - build

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

publish:
  stage: build
  script:
    - ./gradlew publish
  artifacts:
    paths:
      - build/libs/*.jar
    expire_in: 1 week
  only:
    - master

build:
  stage: build
  script: ./gradlew build
  only:
    - merge_requests
